### ISSUE TITLE
No package matching 'php7.0' is available

### ISSUE THREAD

**Issue by adamplabarge** [Mayccoll/Vagrant-Ansible-Wordpress#1]
Hi - Using the default you have setup here, SSH is unable to connect to the server.  I also tried the bento box you have in a basic vagrant setup, SSH would not work there as well.  So something might have updated that is causing issues.

**Comment by adamplabarge** [comment]
As a side note - without changing the config files at all, I'm having no luck SSH'ing into the VM via any of the adapters.  Using VirtualBox.

**Comment by Mayccoll** [comment]
Yep your right
Works with ```bento/ubuntu-16.04``` version 2.2.9  but with version 2.3.0 is not working.
I'm going to check with another box

**Comment by adamplabarge** [comment]
I got a version working with ubuntu/trusty 14.04 but I had to add a different remote repository to be able to get the PHP packages to install.

`    # repo add as ubuntu/trusty does not have php7 packages
    - name          : Switching to ppa:ondrej/php repository
      apt_repository: repo="ppa:ondrej/php"

    - name       : Install PHP and its modules
      apt        :
        pkg      : "{{ item }}"
        state    : latest
      with_items :
        - php5.6
        - php5.6-cli
        - php5.6-curl
        - php5.6-gd
        - php5.6-mysql
        - php5.6-xmlrpc
        - php5.6-json
        - php5.6-cgi
        - php-imagick
        - php5.6-mbstring
        - php5.6-soap
        - php5.6-dom`

I forked the project and have an ubuntu branch here: https://github.com/adamplabarge/Vagrant-Ansible-Wordpress/tree/ubuntu-trusty

What you have done is super helpful, thanks! I added some changes to my version though, one that creates new WP Salts in a wp-salts.php file - but I'm not psych'd on how I did it.  It would be better to get it to work in the YAML template like the others, but I couldn't figure out how as of yet.

**Comment by Mayccoll** [comment]
I fix this using a specific version of bento box. (03dfa376d)

```yaml
vms:
  - name               : vag-wordpress
    box                : bento/ubuntu-16.04
    box_version        : 2.2.9
```

**Comment by Mayccoll** [comment]
Create my own box using bento.
